ALTER TABLE "MatchAnalysis"
  ALTER COLUMN "jobId" DROP NOT NULL,
  ADD COLUMN "jobDescription" TEXT,
  ADD COLUMN "source" TEXT NOT NULL DEFAULT 'STORED_JOB';

ALTER TABLE "AiRun"
  ADD COLUMN "status" TEXT NOT NULL DEFAULT 'SUCCESS',
  ADD COLUMN "errorCode" TEXT,
  ADD COLUMN "promptVersion" TEXT NOT NULL DEFAULT 'legacy';
