import type { Prisma } from "@prisma/client";

export const DEMO_RECRUITER_PASSWORD = "DemoRecruiter123!";

export const demoCompanies = [
  { slug: "kada-technology", name: "KaDa Technology", location: "TP. Hồ Chí Minh", industry: "SOFTWARE", size: "SIZE_100_499", description: "Công ty sản phẩm số xây dựng nền tảng tuyển dụng và phát triển nghề nghiệp cho kỹ sư phần mềm." },
  { slug: "may-viet-cloud", name: "Mây Việt Cloud", location: "Hà Nội", industry: "INFORMATION_TECHNOLOGY", size: "SIZE_50_99", description: "Đơn vị cung cấp hạ tầng đám mây, nền tảng vận hành và giải pháp bảo mật cho doanh nghiệp Việt." },
  { slug: "du-lieu-sang", name: "Dữ Liệu Sáng", location: "Đà Nẵng", industry: "PROFESSIONAL_SERVICES", size: "SIZE_10_49", description: "Nhóm tư vấn dữ liệu và AI, tập trung vào phân tích có thể kiểm chứng và sản phẩm hỗ trợ ra quyết định." },
  { slug: "vi-sen-digital", name: "Ví Sen Digital", location: "TP. Hồ Chí Minh", industry: "FINANCE_BANKING", size: "SIZE_500_999", description: "Doanh nghiệp công nghệ tài chính phát triển dịch vụ thanh toán an toàn và dễ tiếp cận." },
  { slug: "cho-so-viet", name: "Chợ Số Việt", location: "Hà Nội", industry: "ECOMMERCE", size: "SIZE_1000_PLUS", description: "Nền tảng thương mại điện tử kết nối nhà bán hàng trong nước với người tiêu dùng trên nhiều kênh." },
] as const;

export const demoRecruiters = [
  { email: "recruiter.kada@example.com", name: "Nguyễn Minh Anh", companySlug: "kada-technology" },
  { email: "recruiter.mayviet@example.com", name: "Trần Hải Yến", companySlug: "may-viet-cloud" },
  { email: "recruiter.dulieusang@example.com", name: "Lê Quốc Bảo", companySlug: "du-lieu-sang" },
  { email: "recruiter.visen@example.com", name: "Phạm Thu Hà", companySlug: "vi-sen-digital" },
  { email: "recruiter.chosoviet@example.com", name: "Đỗ Hoàng Nam", companySlug: "cho-so-viet" },
] as const;

type DemoJob = Omit<Prisma.JobUncheckedCreateInput, "companyId"> & { companySlug: string };
const benefits = "Lương tháng 13; bảo hiểm đầy đủ; ngân sách học tập; khám sức khỏe định kỳ; thiết bị làm việc theo nhu cầu.";

function job(input: DemoJob): DemoJob {
  return { salaryCurrency: "VND", source: "DEMO_REFERENCE", status: "PUBLISHED", benefits, ...input };
}

export const demoJobs: DemoJob[] = [
  job({ id: "demo-kada-frontend", companySlug: "kada-technology", company: "KaDa Technology", title: "Lập trình viên Frontend React", location: "TP. Hồ Chí Minh", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "MID", salaryMin: 25000000, salaryMax: 40000000, skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"], description: "Phát triển trải nghiệm tuyển dụng có hiệu năng cao, dễ tiếp cận và nhất quán trên nhiều thiết bị.", requirements: "Từ 2 năm kinh nghiệm React; vững TypeScript và accessibility; biết viết kiểm thử; phối hợp tốt với thiết kế và backend." }),
  job({ id: "demo-kada-backend", companySlug: "kada-technology", company: "KaDa Technology", title: "Kỹ sư Backend Node.js", location: "TP. Hồ Chí Minh", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "SENIOR", salaryMin: 35000000, salaryMax: 55000000, skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis"], description: "Thiết kế dịch vụ xử lý hồ sơ, đối sánh công việc và luồng đánh giá có khả năng mở rộng.", requirements: "Từ 4 năm phát triển backend; hiểu API, SQL và hàng đợi; có kinh nghiệm bảo mật dữ liệu và quan sát hệ thống." }),
  job({ id: "demo-kada-designer", companySlug: "kada-technology", company: "KaDa Technology", title: "Nhà thiết kế UI/UX", location: "Làm việc từ xa", department: "DESIGN", employmentType: "FULL_TIME", workMode: "REMOTE", experienceLevel: "MID", salaryMin: 22000000, salaryMax: 35000000, skills: ["Figma", "Design System", "User Research"], description: "Nghiên cứu và thiết kế hành trình ứng viên, nhà tuyển dụng trên nền tảng web.", requirements: "Có portfolio; thành thạo Figma; hiểu thiết kế đáp ứng và accessibility; giao tiếp rõ ràng với nhóm sản phẩm." }),
  job({ id: "demo-mayviet-devops", companySlug: "may-viet-cloud", company: "Mây Việt Cloud", title: "Kỹ sư DevOps", location: "Hà Nội", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "ONSITE", experienceLevel: "MID", salaryMin: 30000000, salaryMax: 48000000, skills: ["AWS", "Docker", "Kubernetes", "Terraform"], description: "Xây dựng nền tảng triển khai tự động, quan sát hệ thống và chuẩn hóa hạ tầng bằng mã.", requirements: "Từ 2 năm vận hành Linux; kinh nghiệm container và CI/CD; hiểu mạng, bảo mật và xử lý sự cố sản xuất." }),
  job({ id: "demo-mayviet-platform", companySlug: "may-viet-cloud", company: "Mây Việt Cloud", title: "Kỹ sư nền tảng đám mây", location: "Hà Nội", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "SENIOR", salaryMin: 40000000, salaryMax: 65000000, skills: ["AWS", "Kubernetes", "Go", "Observability"], description: "Thiết kế nền tảng self-service giúp đội sản phẩm triển khai an toàn và phục hồi sự cố nhanh.", requirements: "Từ 5 năm về cloud hoặc platform; hiểu SRE và distributed systems; có kinh nghiệm dẫn dắt cải tiến kỹ thuật." }),
  job({ id: "demo-mayviet-sre", companySlug: "may-viet-cloud", company: "Mây Việt Cloud", title: "Kỹ sư Site Reliability", location: "Làm việc từ xa", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "REMOTE", experienceLevel: "MID", salaryMin: 32000000, salaryMax: 50000000, skills: ["Prometheus", "Grafana", "Python", "Linux"], description: "Theo dõi SLI/SLO, tự động hóa vận hành và nâng cao độ tin cậy dịch vụ.", requirements: "Hiểu monitoring, incident response và capacity planning; viết được công cụ tự động hóa; tham gia lịch trực luân phiên." }),
  job({ id: "demo-data-analyst", companySlug: "du-lieu-sang", company: "Dữ Liệu Sáng", title: "Chuyên viên Phân tích dữ liệu", location: "Đà Nẵng", department: "DATA", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "JUNIOR", salaryMin: 18000000, salaryMax: 28000000, skills: ["SQL", "Python", "Power BI", "Statistics"], description: "Phân tích hành vi sản phẩm, xây dựng dashboard và chuyển dữ liệu thành đề xuất có thể hành động.", requirements: "Vững SQL và thống kê cơ bản; biết trực quan hóa; tư duy kiểm chứng giả thuyết; chấp nhận ứng viên mới có dự án tốt." }),
  job({ id: "demo-data-scientist", companySlug: "du-lieu-sang", company: "Dữ Liệu Sáng", title: "Nhà khoa học dữ liệu", location: "Đà Nẵng", department: "DATA", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "MID", salaryMin: 30000000, salaryMax: 48000000, skills: ["Python", "Pandas", "scikit-learn", "Machine Learning"], description: "Xây dựng mô hình dự báo, thiết kế thí nghiệm và trình bày giới hạn của kết quả.", requirements: "Từ 2 năm làm dữ liệu; hiểu thống kê và đánh giá mô hình; giải thích được thiên lệch và độ bất định." }),
  job({ id: "demo-data-ml", companySlug: "du-lieu-sang", company: "Dữ Liệu Sáng", title: "Kỹ sư Machine Learning", location: "Làm việc từ xa", department: "DATA", employmentType: "CONTRACT", workMode: "REMOTE", experienceLevel: "SENIOR", salaryMin: 45000000, salaryMax: 70000000, skills: ["Python", "PyTorch", "MLflow", "Docker"], description: "Đưa mô hình vào sản xuất với khả năng theo dõi chất lượng và truy vết phiên bản.", requirements: "Kinh nghiệm triển khai mô hình production; hiểu data drift, model monitoring và API; ưu tiên từng xây pipeline MLOps." }),
  job({ id: "demo-visen-java", companySlug: "vi-sen-digital", company: "Ví Sen Digital", title: "Lập trình viên Java Spring Boot", location: "TP. Hồ Chí Minh", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "MID", salaryMin: 28000000, salaryMax: 45000000, skills: ["Java", "Spring Boot", "PostgreSQL", "Kafka"], description: "Phát triển dịch vụ thanh toán có tính nhất quán cao, khả năng kiểm toán và chống lỗi tốt.", requirements: "Từ 3 năm Java; hiểu transaction, concurrency và REST API; có ý thức cao về bảo mật và kiểm thử." }),
  job({ id: "demo-visen-product", companySlug: "vi-sen-digital", company: "Ví Sen Digital", title: "Quản lý sản phẩm thanh toán", location: "TP. Hồ Chí Minh", department: "PRODUCT", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "MANAGER", salaryMin: 45000000, salaryMax: 70000000, skills: ["Product Strategy", "Analytics", "Agile", "Fintech"], description: "Định hình lộ trình sản phẩm, cân bằng trải nghiệm khách hàng, tuân thủ và hiệu quả kinh doanh.", requirements: "Từ 5 năm quản lý sản phẩm số; biết dùng dữ liệu ưu tiên vấn đề; có năng lực dẫn dắt nhóm liên chức năng." }),
  job({ id: "demo-visen-qa", companySlug: "vi-sen-digital", company: "Ví Sen Digital", title: "Kỹ sư Kiểm thử tự động", location: "TP. Hồ Chí Minh", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "ONSITE", experienceLevel: "MID", salaryMin: 24000000, salaryMax: 38000000, skills: ["Playwright", "API Testing", "TypeScript", "CI/CD"], description: "Thiết kế chiến lược kiểm thử và tự động hóa các luồng thanh toán quan trọng.", requirements: "Từ 2 năm automation testing; hiểu test pyramid; phân tích rủi ro và viết báo cáo lỗi rõ ràng." }),
  job({ id: "demo-market-mobile", companySlug: "cho-so-viet", company: "Chợ Số Việt", title: "Lập trình viên React Native", location: "Hà Nội", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "MID", salaryMin: 26000000, salaryMax: 42000000, skills: ["React Native", "TypeScript", "iOS", "Android"], description: "Phát triển ứng dụng mua sắm đa nền tảng và tối ưu hiệu năng trên thiết bị phổ thông.", requirements: "Từ 2 năm React Native; hiểu vòng đời ứng dụng và native bridge; biết theo dõi crash và phát hành ứng dụng." }),
  job({ id: "demo-market-fullstack", companySlug: "cho-so-viet", company: "Chợ Số Việt", title: "Lập trình viên Full-stack MERN", location: "Hà Nội", department: "ENGINEERING", employmentType: "FULL_TIME", workMode: "HYBRID", experienceLevel: "JUNIOR", salaryMin: 18000000, salaryMax: 30000000, skills: ["MongoDB", "Express", "React", "Node.js"], description: "Xây dựng tính năng quản lý gian hàng và công cụ vận hành cho nhà bán hàng.", requirements: "Từ 1 năm hoặc có dự án MERN hoàn chỉnh; hiểu Git, REST API và kiểm thử cơ bản; chủ động học qua phản hồi mã nguồn." }),
  job({ id: "demo-market-recruiter", companySlug: "cho-so-viet", company: "Chợ Số Việt", title: "Thực tập sinh Tuyển dụng Công nghệ", location: "Hà Nội", department: "HUMAN_RESOURCES", employmentType: "INTERNSHIP", workMode: "ONSITE", experienceLevel: "INTERN", salaryMin: 4000000, salaryMax: 7000000, skills: ["Sourcing", "Communication", "Interview Coordination"], description: "Hỗ trợ tìm kiếm ứng viên kỹ thuật, điều phối phỏng vấn và duy trì dữ liệu tuyển dụng chính xác.", requirements: "Sinh viên năm cuối; giao tiếp tốt; cẩn thận với dữ liệu cá nhân; có thể làm tối thiểu 4 ngày mỗi tuần." }),
];
